# Generated by Django 3.1.7 on 2022-09-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(verbose_name='Numero Celular')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('facebook', models.CharField(max_length=500, verbose_name='Facebook')),
                ('instagram', models.CharField(max_length=500, verbose_name='Instagram')),
                ('youtube', models.CharField(max_length=500, verbose_name='Youtube')),
                ('Direccion', models.CharField(max_length=500, verbose_name='Youtube')),
            ],
        ),
        migrations.CreateModel(
            name='en_vivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('url', models.CharField(max_length=500, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='nav_bar_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('posicion', models.IntegerField(verbose_name='Posicion en navegador')),
            ],
        ),
        migrations.CreateModel(
            name='tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('tipo', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('lanzamiento', models.DateField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
