# Generated by Django 3.1.7 on 2022-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_bar_opt',
            name='link_contenido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Palabra Link de contenido'),
        ),
    ]
