# Generated by Django 3.1.7 on 2022-09-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_nav_bar_opt_link_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='biografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.IntegerField(verbose_name='Numero Celular')),
                ('desc_one', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('desc_two', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('imagen_one', models.CharField(max_length=500, verbose_name='Facebook')),
                ('imagen_two', models.CharField(max_length=500, verbose_name='Facebook')),
                ('imagen_three', models.CharField(max_length=500, verbose_name='Facebook')),
            ],
        ),
    ]
