# Generated by Django 3.1.7 on 2022-10-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_tracks_url_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='url_img',
        ),
    ]
