# Generated by Django 3.1.7 on 2022-09-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Track'),
        ),
    ]
