# Generated by Django 3.1.7 on 2022-09-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_tracks_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='url',
        ),
        migrations.AddField(
            model_name='tracks',
            name='pista',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
