# Generated by Django 3.1.7 on 2022-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20220927_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biografia',
            name='desc_one',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='desc_two',
        ),
        migrations.AddField(
            model_name='biografia',
            name='desc_prim',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion integrante 1'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='desc_princ',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion principal'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='desc_seg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion integrante 2'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='integrante_dos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Integrante 2'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='integrante_uno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Integrante 1'),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='imagen_one',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='imagen_three',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='imagen_two',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='tipo',
            field=models.CharField(choices=[('0', 'Cancion'), ('1', 'Beat'), ('2', 'Instrumental')], max_length=500, verbose_name='Tipo'),
        ),
    ]
