# Generated by Django 3.1.7 on 2022-09-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20220928_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biografia',
            name='imagen_one',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='imagen_three',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='biografia',
            name='imagen_two',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 2'),
        ),
    ]
