# Generated by Django 3.1.7 on 2022-09-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20220929_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='en_vivo',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='en_vivo',
            name='fecha_grabacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
