# Generated by Django 3.1.7 on 2022-10-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20220929_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_bar_opt',
            name='icono',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Icono'),
        ),
    ]
