# Generated by Django 3.1.7 on 2022-10-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_nav_bar_opt_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav_bar_opt',
            name='icono',
        ),
    ]
