# Generated by Django 3.1.7 on 2022-10-02 01:24

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_remove_nav_bar_opt_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_vivo',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
